import 'dart:ui';
import 'package:flutter/material.dart';
import '../../core/app_export.dart';

String _appTheme = "primary";

/// Helper class for managing themes and colors.
class ThemeHelper {
  // A map of custom color themes supported by the app
  Map<String, PrimaryColors> _supportedCustomColor = {
    'primary': PrimaryColors()
  };

// A map of color schemes supported by the app
  Map<String, ColorScheme> _supportedColorScheme = {
    'primary': ColorSchemes.primaryColorScheme
  };

  /// Changes the app theme to [_newTheme].
  void changeTheme(String _newTheme) {
    _appTheme = _newTheme;
  }

  /// Returns the primary colors for the current theme.
  PrimaryColors _getThemeColors() {
    //throw exception to notify given theme is not found or not generated by the generator
    if (!_supportedCustomColor.containsKey(_appTheme)) {
      throw Exception(
          "$_appTheme is not found.Make sure you have added this theme class in JSON Try running flutter pub run build_runner");
    }
    //return theme from map

    return _supportedCustomColor[_appTheme] ?? PrimaryColors();
  }

  /// Returns the current theme data.
  ThemeData _getThemeData() {
    //throw exception to notify given theme is not found or not generated by the generator
    if (!_supportedColorScheme.containsKey(_appTheme)) {
      throw Exception(
          "$_appTheme is not found.Make sure you have added this theme class in JSON Try running flutter pub run build_runner");
    }
    //return theme from map

    var colorScheme =
        _supportedColorScheme[_appTheme] ?? ColorSchemes.primaryColorScheme;
    return ThemeData(
      colorScheme: colorScheme,
      elevatedButtonTheme: ElevatedButtonThemeData(
        style: ElevatedButton.styleFrom(
          backgroundColor: colorScheme.primary,
          shape: RoundedRectangleBorder(
            borderRadius: BorderRadius.circular(
              5,
            ),
          ),
        ),
      ),
      textTheme: TextTheme(
        bodyMedium: TextStyle(
          color: appTheme.black900,
          fontSize: getFontSize(
            14,
          ),
          fontFamily: 'Graphik',
          fontWeight: FontWeight.w400,
        ),
        bodySmall: TextStyle(
          color: appTheme.gray400,
          fontSize: getFontSize(
            12,
          ),
          fontFamily: 'Graphik',
          fontWeight: FontWeight.w400,
        ),
        titleSmall: TextStyle(
          color: colorScheme.onPrimary,
          fontSize: getFontSize(
            14,
          ),
          fontFamily: 'Graphik',
          fontWeight: FontWeight.w700,
        ),
        titleMedium: TextStyle(
          color: appTheme.black900,
          fontSize: getFontSize(
            16,
          ),
          fontFamily: 'Graphik',
          fontWeight: FontWeight.w700,
        ),
        labelLarge: TextStyle(
          color: appTheme.indigoA200,
          fontSize: getFontSize(
            12,
          ),
          fontFamily: 'Graphik',
          fontWeight: FontWeight.w700,
        ),
      ),
      visualDensity: VisualDensity.standard,
    );
  }

  /// Returns the primary colors for the current theme.
  PrimaryColors themeColor() => _getThemeColors();

  /// Returns the current theme data.
  ThemeData themeData() => _getThemeData();
}

/// Class containing the supported color schemes.
class ColorSchemes {
  static final primaryColorScheme = ColorScheme.light(
    background: Color(0XFFFFFFFF),
    error: Color(0XFFFFFFFF),
    errorContainer: Color(0XFFBF2F30),
    inversePrimary: Color(0XFFFFFFFF),
    inverseSurface: Color(0XFFFFFFFF),
    onBackground: Color(0XFF263238),
    onError: Color(0XFF263238),
    onErrorContainer: Color(0XFFFFFFFF),
    onInverseSurface: Color(0XFF263238),
    onPrimary: Color(0XFFFFFFFF),
    onPrimaryContainer: Color(0XFF263238),
    onSecondary: Color(0XFF263238),
    onSecondaryContainer: Color(0XFFFFFFFF),
    onSurface: Color(0XFF263238),
    onSurfaceVariant: Color(0XFFFFFFFF),
    onTertiary: Color(0XFF263238),
    onTertiaryContainer: Color(0XFFFFFFFF),
    outline: Color(0XFFFFFFFF),
    outlineVariant: Color(0XFFFFFFFF),
    primary: Color(0XFFBF2F30),
    primaryContainer: Color(0XFFFFFFFF),
    scrim: Color(0XFFFFFFFF),
    secondary: Color(0XFFFFFFFF),
    secondaryContainer: Color(0XFFBF2F30),
    shadow: Color(0XFFFFFFFF),
    surface: Color(0XFFFFFFFF),
    surfaceTint: Color(0XFFFFFFFF),
    surfaceVariant: Color(0XFFBF2F30),
    tertiary: Color(0XFFFFFFFF),
    tertiaryContainer: Color(0XFFBF2F30),
  );
}

/// Class containing custom colors for a primary theme.
class PrimaryColors {
  // Black
  Color get black900 => Color(0XFF000000);
  // BlueGray
  Color get blueGray100 => Color(0XFFD9D9D9);
  Color get blueGray400 => Color(0XFF888888);
  // Gray
  Color get gray100 => Color(0XFFF6F6F6);
  Color get gray10001 => Color(0XFFF5F5F5);
  Color get gray300 => Color(0XFFE6E6E6);
  Color get gray30001 => Color(0XFFDADADA);
  Color get gray400 => Color(0XFFAFAFAF);
  Color get gray500 => Color(0XFF979797);
  Color get gray900 => Color(0XFF200E32);
  // Indigo
  Color get indigoA200 => Color(0XFF5B61F4);
  // LightGreen
  Color get lightGreen60023 => Color(0X2365BF2E);
  Color get lightGreen900 => Color(0XFF307804);
  // Pink
  Color get pink300 => Color(0XFFFB7181);
}

PrimaryColors get appTheme => ThemeHelper().themeColor();
ThemeData get theme => ThemeHelper().themeData();
